export const INDIAN_AIRPORTS = [
  { code: "DEL", name: "Indira Gandhi International Airport, New Delhi" },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport, Mumbai" },
  { code: "BLR", name: "Kempegowda International Airport, Bengaluru" },
  { code: "HYD", name: "Rajiv Gandhi International Airport, Hyderabad" },
  { code: "MAA", name: "Chennai International Airport, Chennai" },
  { code: "CCU", name: "Netaji Subhas Chandra Bose International Airport, Kolkata" },
  { code: "AMD", name: "Sardar Vallabhbhai Patel International Airport, Ahmedabad" },
  { code: "COK", name: "Cochin International Airport, Kochi" },
  { code: "GOI", name: "Goa International Airport (Dabolim), Goa" },
  { code: "PNQ", name: "Pune International Airport, Pune" },
  { code: "JAI", name: "Jaipur International Airport, Jaipur" },
  { code: "LKO", name: "Chaudhary Charan Singh International Airport, Lucknow" },
  { code: "IXC", name: "Shaheed Bhagat Singh International Airport, Chandigarh" },
  { code: "BBI", name: "Biju Patnaik International Airport, Bhubaneswar" },
  { code: "TRV", name: "Trivandrum International Airport, Thiruvananthapuram" },
  { code: "IXE", name: "Mangalore International Airport, Mangaluru" },
  { code: "IXM", name: "Madurai International Airport, Madurai" },
  { code: "CJB", name: "Coimbatore International Airport, Coimbatore" },
  { code: "VGA", name: "Vijayawada International Airport, Vijayawada" },
  { code: "VTZ", name: "Visakhapatnam International Airport, Visakhapatnam" },
  { code: "PAT", name: "Jay Prakash Narayan International Airport, Patna" },
  { code: "RPR", name: "Swami Vivekananda Airport, Raipur" },
  { code: "GAU", name: "Lokpriya Gopinath Bordoloi International Airport, Guwahati" },
  { code: "IMF", name: "Imphal International Airport, Imphal" },
  { code: "IXA", name: "Maharaja Bir Bikram Airport, Agartala" },
  { code: "IXR", name: "Birsa Munda Airport, Ranchi" },
  { code: "IXZ", name: "Veer Savarkar International Airport, Port Blair" },
  { code: "TIR", name: "Tirupati Airport, Tirupati" },
  { code: "HBX", name: "Hubli Airport, Hubli" },
  { code: "UDR", name: "Maharana Pratap Airport, Udaipur" },
  { code: "JDH", name: "Jodhpur Airport, Jodhpur" },
  { code: "BDQ", name: "Vadodara Airport, Vadodara" },
  { code: "STV", name: "Surat Airport, Surat" },
  { code: "IXJ", name: "Jammu Airport, Jammu" },
  { code: "SXR", name: "Sheikh ul-Alam International Airport, Srinagar" },
  { code: "IXL", name: "Kushok Bakula Rimpochee Airport, Leh" },
  { code: "GAY", name: "Gaya Airport, Gaya" },
  { code: "DIB", name: "Dibrugarh Airport, Dibrugarh" },
  { code: "JRH", name: "Jorhat Airport, Jorhat" },
  { code: "TEZ", name: "Tezpur Airport, Tezpur" },
  { code: "SHL", name: "Shillong Airport, Shillong" },
  { code: "AJL", name: "Lengpui Airport, Aizawl" },
  { code: "DMU", name: "Dimapur Airport, Dimapur" },
  { code: "KNU", name: "Kanpur Airport, Kanpur" },
  { code: "GWL", name: "Gwalior Airport, Gwalior" },
  { code: "BHO", name: "Raja Bhoj Airport, Bhopal" },
  { code: "IDR", name: "Devi Ahilya Bai Holkar Airport, Indore" },
  { code: "NAG", name: "Dr. Babasaheb Ambedkar International Airport, Nagpur" },
  { code: "NDC", name: "Nanded Airport, Nanded" },
  { code: "JLR", name: "Jabalpur Airport, Jabalpur" },
  { code: "BHJ", name: "Bhuj Airport, Bhuj" },
  { code: "RAJ", name: "Rajkot Airport, Rajkot" },
  { code: "BHU", name: "Bhavnagar Airport, Bhavnagar" },
  { code: "IXG", name: "Belgaum Airport, Belagavi" },
  { code: "HJR", name: "Khajuraho Airport, Khajuraho" },
  { code: "REW", name: "Rewa Airport, Rewa" },
  { code: "PYG", name: "Pakyong Airport, Pakyong" },
  { code: "DIU", name: "Diu Airport, Diu" },
  { code: "PBD", name: "Porbandar Airport, Porbandar" },
  { code: "IXD", name: "Allahabad Airport (Prayagraj), Prayagraj" },
  { code: "GOP", name: "Gorakhpur Airport, Gorakhpur" },
  { code: "LUH", name: "Ludhiana Airport, Ludhiana" },
  { code: "SLV", name: "Shimla Airport, Shimla" },
  { code: "DHM", name: "Gaggal Airport (Kangra), Dharamshala" },
  { code: "KUU", name: "Kullu-Manali Airport (Bhuntar), Kullu" },
  { code: "JGA", name: "Jamnagar Airport, Jamnagar" },
  { code: "IXU", name: "Aurangabad Airport (Chikkalthana), Aurangabad" },
  { code: "SSE", name: "Shirdi Airport, Shirdi" },
  { code: "OMN", name: "Osmanabad Airport, Osmanabad" },
  { code: "KLH", name: "Kolhapur Airport, Kolhapur" },
  { code: "IXT", name: "Pasighat Airport, Pasighat" },
  { code: "LUZ", name: "Latur Airport, Latur" },
  { code: "RGH", name: "Balurghat Airport, Balurghat" },
  { code: "CCJ", name: "Calicut International Airport, Kozhikode" },
  { code: "TRZ", name: "Tiruchirappalli International Airport, Tiruchirappalli" },
  { code: "CNN", name: "Kannur International Airport, Kannur" },
  { code: "SXV", name: "Salem Airport, Salem" },
  { code: "TNJ", name: "Tuticorin Airport, Thoothukudi" },
  { code: "WGC", name: "Warangal Airport, Warangal" },
  { code: "SAG", name: "Shirdi Airport, Shirdi" },
  { code: "RYP", name: "Ras Al Khaimah Airport (Raipur), Raipur" },
  { code: "JGB", name: "Jagdalpur Airport, Jagdalpur" },
  { code: "PGH", name: "Pantnagar Airport, Pantnagar" },
  { code: "CDP", name: "Cuddapah Airport, Kadapa" },
  { code: "RJY", name: "Rajahmundry Airport, Rajahmundry" },
  { code: "TCR", name: "Tuticorin Airport, Tuticorin" },
  { code: "HSS", name: "Hissar Airport, Hisar" },
  { code: "KJB", name: "Kurnool Airport, Kurnool" },
  { code: "MYQ", name: "Mysore Airport, Mysuru" },
  { code: "AGR", name: "Agra Airport (Pandit Deen Dayal Upadhyay), Agra" },
  { code: "DHM", name: "Kangra Airport (Gaggal), Dharamshala" },
  { code: "SLV", name: "Shimla Airport, Shimla" },
  { code: "BUP", name: "Bathinda Airport, Bathinda" },
  { code: "LUH", name: "Ludhiana Airport, Ludhiana" }
];

export const airportOptions = INDIAN_AIRPORTS.map(a => ({
  value: `${a.code} - ${a.name}`,
  label: `${a.code} - ${a.name}`,
  code: a.code,
  name: a.name
}));

export function findAirportOption(value) {
  if (!value) return null;
  return airportOptions.find(opt =>
    opt.value === value ||
    opt.code === value ||
    value.startsWith(opt.code)
  ) || null;
}
